Test problem RE21
industrial-optimization-group/DESDEO pull request #111
Opened 2024-06-20 07:28 UTC by Matskuu

Implemented the RE21 test problem in desdeo2 format. Added a page for test problem documentations and added some documentation for the RE21 problem. However, I could not find much information about the problem, so at the moment the description is a bit stale.

2024-06-25 13:25 UTC, gialmisi requested changes
Please address the two comments I left and update the PR.

2024-06-25 13:25 UTC, gialmisi commented on desdeo/problem/testproblems.py
> +    # should these be hardcoded here or given as optional arguments for the problem?
Add these as optional arguments with default values set to the current values given to them.

2024-06-25 13:25 UTC, gialmisi commented on desdeo/problem/testproblems.py
> +        is_convex=True
Explicitly state for each Objective if it is convex or not, is it linear or not, and is it twice differentiable or not. Double check whether this function is convex or not not (I believe it is concave...).

2024-07-03 11:46 UTC, juropo commented
Unnecessary, because these are included in a later pull request

2024-07-03 11:46 UTC, closed without merging